package domain.checks;

import domain.ClassInfo;
import domain.FieldInfo;
import domain.Severity;
import domain.checks.LintIssue;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

/**
 * Field Naming Convention Check
 * 
 * Checks that fields follow Java naming conventions:
 * - Constants (static final) should be UPPER_SNAKE_CASE
 * - Other fields should be camelCase
 */
public class FieldNamingCheck implements StyleCheck {

    // Pattern for constants: UPPER_SNAKE_CASE (e.g., MAX_VALUE, DEFAULT_SIZE)
    private static final Pattern UPPER_SNAKE_CASE = Pattern.compile("^[A-Z][A-Z0-9_]*$");
    
    // Pattern for regular fields: camelCase (e.g., firstName, totalCount)
    private static final Pattern CAMEL_CASE = Pattern.compile("^[a-z][a-zA-Z0-9]*$");

    @Override
    public String getName() {
        return "FieldNamingCheck";
    }

    @Override
    public String getDescription() {
        return "Checks that constants are UPPER_SNAKE_CASE and other fields are camelCase";
    }

    @Override
    public List<LintIssue> check(ClassInfo classInfo) {
        List<LintIssue> issues = new ArrayList<>();

        // Skip interfaces (they only have constants anyway)
        if (classInfo.isInterface()) {
            return issues;
        }

        for (FieldInfo field : classInfo.getFields()) {
            String fieldName = field.getName();
            String location = classInfo.getName() + "." + fieldName;

            // Skip synthetic fields (generated by compiler)
            if (fieldName.contains("$")) {
                continue;
            }

            // Check if it's a constant (static final)
            if (field.isStatic() && field.isFinal()) {
                // Constants should be UPPER_SNAKE_CASE
                if (!UPPER_SNAKE_CASE.matcher(fieldName).matches()) {
                    issues.add(new LintIssue(
                        getName(),
                        Severity.WARNING,
                        String.format(
                            "Constant '%s' should be UPPER_SNAKE_CASE (e.g., MAX_VALUE, DEFAULT_SIZE). " +
                            "Java convention: constants use uppercase letters with underscores in %s",
                            fieldName, location
                        )
                    ));
                }
            } else {
                // Regular fields should be camelCase
                if (!CAMEL_CASE.matcher(fieldName).matches()) {
                    // Determine what's wrong with the name
                    String suggestion = getSuggestion(fieldName);
                    
                    issues.add(new LintIssue(
                        getName(),
                        Severity.WARNING,
                        String.format(
                            "Field '%s' should be camelCase (e.g., firstName, totalCount). %s in %s",
                            fieldName, suggestion, location
                        )
                    ));
                }
            }
        }

        return issues;
    }

    // Get a specific suggestion based on what's wrong with the field name.
    private String getSuggestion(String fieldName) {
        if (fieldName.isEmpty()) {
            return "Field name cannot be empty.";
        }
        if (Character.isUpperCase(fieldName.charAt(0))) {
            return "Field names should start with a lowercase letter.";
        }
        if (fieldName.contains("_")) {
            return "Regular fields should not contain underscores. Use camelCase instead.";
        }
        if (fieldName.startsWith("m_") || fieldName.startsWith("_")) {
            return "Avoid Hungarian notation or leading underscores in Java.";
        }
        return "Java convention: field names use camelCase.";
    }
}
